Log a warning instead of cutting job execution when commit notification is sent
jenkinsci/tuleap-api-plugin pull request #163
Opened 2021-06-14 13:41 UTC by robinsoc

[request #21785](https://tuleap.net/plugins/tracker/?aid=21785) Errors on auto-notify should be printed but not taken into account as a failure

How to test:
     - Run a job which fails because of Tuleap REST API response
    => In the Jenkins Log, the error is displayed
    => The job still running until the end.

2021-06-14 14:54 UTC, Erwyn requested changes

2021-06-14 14:54 UTC, Erwyn commented on src/main/java/io/jenkins/plugins/tuleap_api/client/GitApi.java
> +    void sendBuildStatusWithWarningLog(String repositoryId, String commitReference, TuleapBuildStatus status, StringCredentials credentials);
We don't need this one.

2021-06-14 14:54 UTC, Erwyn commented on src/main/java/io/jenkins/plugins/tuleap_api/client/internals/TuleapApiClient.java
> +    public void sendBuildStatusWithWarningLog(String repositoryId, String commitReference, TuleapBuildStatus status, StringCredentials credentials) {
we don't need this

2021-07-05 09:51 UTC, robinsoc commented
After internal discussion this PR seems not needed anymore.
Let's close this one.

2021-07-05 09:51 UTC, closed without merging